rentACarProject/Models/AddCustomerViewModel.cs
namespace rentACarProject.Models
{
    public class AddCustomerViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Adress { get; set; }
        public int contactNumber { get; set; }

        
    }
}

rentACarProject/Models/Domain/Car.cs
namespace rentACarProject.Models.Domain
{
    public class Car
    {
         public Guid Id { get; set; }
         public int carYear { get; set; }
         public string carModelName { get; set; }
         public int rentPrice{ get; set; }

        
         
    }
}

rentACarProject/Models/Domain/Customer.cs
namespace rentACarProject.Models.Domain
{
    public class Customer
    {
        public Guid Id { get; set; } 
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Adress { get; set; }
        public int contactNumber { get; set; }
       



    }
}

rentACarProject/Models/ErrorViewModel.cs
namespace rentACarProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

rentACarProject/Models/UpdateCustomerViewModel.cs
namespace rentACarProject.Models
{
    public class UpdateCustomerViewModel
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Adress { get; set; }
        public int contactNumber { get; set; }

    }
}

rentACarProject/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;

namespace rentACarProject.Controllers
{
    public class CarsController : Controller
    {
        
        public IActionResult Show()
        {
            return View();
        }
    }
}

rentACarProject/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.Internal;
using rentACarProject.Data;
using rentACarProject.Models;
using rentACarProject.Models.Domain;

namespace rentACarProject.Controllers
{


    public class CustomersController : Controller
    {
        private readonly Database database;

        public CustomersController(Database database)
        {
            this.database = database;
        }

        
        public async Task <IActionResult> Index()
        {
            var customers=await database.Müşteriler.ToListAsync(); // listelemek için
            return View(customers);
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddCustomerViewModel addCustomerRequest)
        {
            var customer = new Customer()
            {
                Id = Guid.NewGuid(),
                FirstName = addCustomerRequest.FirstName,
                LastName = addCustomerRequest.LastName,
                Adress = addCustomerRequest.Adress,
                contactNumber = addCustomerRequest.contactNumber
            };

            await database.Müşteriler.AddAsync(customer);//müşterinin eklenmesi
            await database.SaveChangesAsync();
            return RedirectToAction("Index"); // müşteri eklendikten sonra Index sayfasına yönlendirsin.
            
        } //müşteri ekleme isteği

        [HttpGet]
        public async Task<IActionResult> View(Guid id) //id'ye bakarak veritabanındaki müşteri olduğunu doğrulamaya çalışıyoruz.
        {
            var customer =await database.Müşteriler.FirstOrDefaultAsync(x => x.Id == id);
            // tek bir müşteriyi id'den kontrol ediyoruz.

            if (customer != null) 
            { //eğer kontrol edilebilecek bir müşteri varsa işlemi gerçekleştir.
                  var viewModel = new UpdateCustomerViewModel() // artık buradaki bilgileri kontrol edip görüntüleyeceğiz.
                  {
                       Id = customer.Id,
                       FirstName = customer.FirstName,
                       LastName = customer.LastName,
                       Adress = customer.Adress,
                       contactNumber = customer.contactNumber
                  }; // bu verileri kullanabilmek için async method kullanıyoruz


                return await Task.Run(() => View("View",viewModel)); // müşterilerde görüntüleyip , müşterinin olup olmadığını kontrol edeceğiz
            }

            return RedirectToAction("Index"); // Eğer müşteri yoksa indexe geri yönlendirecek
        }

        [HttpPost] // güncellenen bilgiyi post edeceğiz ve müşterilerin olduğu ekrana geri döneceğiz.
        public async Task <IActionResult> View(UpdateCustomerViewModel model) //formdaki bilgileri günceller.
        {
            var customer = await database.Müşteriler.FindAsync(model.Id);  //get the customer from database

            if(customer != null)
            {
                customer.FirstName = model.FirstName; // güncelennecek olan yerden(model) gelecek bilgi atanır.
                customer.LastName = model.LastName;
                customer.Adress = model.Adress;
                customer.contactNumber = model.contactNumber;

                await database.SaveChangesAsync(); // değişikliklerin kaydedilmesi , async metod olduğunda await eklendi.

                return RedirectToAction("Index"); // kayıttan sonra direkt müşteriler gözüksün
            };
            return RedirectToAction("Index"); // metod çalışmazsa direkt Index gözükür
        }

        [HttpPost]
        public async Task<IActionResult>Delete(UpdateCustomerViewModel model)
        {
            var customer = await database.Müşteriler.FindAsync(model.Id);
            if (customer != null)
            {
                database.Müşteriler.Remove(customer); // müşteriyi sil
                await database.SaveChangesAsync();//değişiklikleri kaydediyoruz.

                return RedirectToAction("Index"); //sildikten sonra müşterilerin olduğu sayfaya dönecek
            }

            return RedirectToAction("Index"); // eğer işlem yapılmazsa direkt Indexe geri dönecek
        }
    }
}

rentACarProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using rentACarProject.Models;
using rentACarProject.Models;
using rentACarProject.Models.Domain;
using System.Diagnostics;

namespace rentACarProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

rentACarProject/Views/Cars/Show.cshtml
@{

}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Araç Model Yılı</th>
            <th>Araç Model İsmi</th>
            <th>Araç Kiralama Ücreti</th>
            <th>Uygunluk Durumu Sorgulama</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>2021</td>
            <td>Toyota Camry</td>
            <td>₺70/günlük</td>
            <td>12.03.2023 - 15.03.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2021</td>
            <td>Honda Accord</td>
            <td>₺120/günlük</td>
            <td>16.03.2023 - 20.03.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2022</td>
            <td>Tesla Model S</td>
            <td>₺550/günlük</td>
            <td>21.03.2023 - 24.03.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2023</td>
            <td>BMW 7 Series</td>
            <td>₺300/günlük</td>
            <td>25.03.2023 - 27.03.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2020</td>
            <td>Ford Mustang</td>
            <td>₺385/günlük</td>
            <td>28.03.2023 - 29.03.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2020</td>
            <td>Skoda Fabia</td>
            <td>₺125/günlük</td>
            <td>01.04.2023 - 03.04.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2018</td>
            <td>Renault Clio</td>
            <td>₺185/günlük</td>
            <td>05.04.2023 - 07.04.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2020</td>
            <td>Fiat Egea</td>
            <td>₺145/günlük</td>
            <td>09.04.2023 - 12.04.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2017</td>
            <td>Volkswagen Golf 5</td>
            <td>₺100/günlük</td>
            <td>18.04.2023 - 23.04.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
        <tr>
            <td>2022</td>
            <td>Audi A7</td>
            <td>₺350/günlük</td>
            <td>25.04.2023 - 29.04.2023 Tarihleri Arasında Kiralanabilir</td>
        </tr>
    </tbody>
</table>

rentACarProject/Views/Customers/Add.cshtml
@model rentACarProject.Models.AddCustomerViewModel

@{
}
<h1>Müşteri Ekleme Ekranı</h1>
<form method ="post" action="Add" class="mt-5">
    <div class="form-group">
        <label for="" class="form-label">Müşteri Adı :</label>
        <input type="text" class="form-control" asp-for="FirstName">
    </div>
    <div class="form-group">
        <label for="" class="form-label">Müşteri Soyadı :</label>
        <input type="text" class="form-control" asp-for="LastName">
    </div>
    <div class="form-group">
        <label for="" class="form-label">Adres :</label>
        <input type="text" class="form-control" asp-for="Adress">
    </div>
    <div class="form-group">
        <label for="" class="form-label">Cep Numarası :</label>
        <input type="number" class="form-control" asp-for="contactNumber">
    </div><br>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

rentACarProject/Views/Customers/Index.cshtml
@model List<rentACarProject.Models.Domain.Customer>


@{
}
<!--vertibanından gelen bilgileri döner ve ekrana listeler.--> 
<h1>Müşteriler</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Müşteri Adı</th>
            <th>Müşteri Soyadı</th>
            <th>Adres</th>
            <th>Numara</th>
            <th>Detayları Görüntüle</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var customer in Model)
        {
            <tr>
                <td>@customer.Id</td>
                <td>@customer.FirstName</td>
                <td>@customer.LastName</td>
                <td>@customer.Adress</td>
                <td>@customer.contactNumber</td>
                <td><a href="Customers/View/@customer.Id">View</a></td> <!--Controllerdaki Customers yazılır.-->
            </tr>
        }
    </tbody>
</table>

rentACarProject/Views/Customers/View.cshtml
@model rentACarProject.Models.UpdateCustomerViewModel

@{
}
<h1>Müşteri Düzenleme Ekranı</h1>
<form method="post" action="View" class="mt-5">
    <div class="form-group">
        <label for="" class="form-label">Id:</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
        <!-- kullanıcı herhangi değişiklik yapamasın -->
    </div>
    <div class="form-group">
        <label for="" class="form-label">Müşteri Adı :</label>
        <input type="text" class="form-control" asp-for="FirstName">
    </div>
    <div class="form-group">
        <label for="" class="form-label">Müşteri Soyadı :</label>
        <input type="text" class="form-control" asp-for="LastName">
    </div>
    <div class="form-group">
        <label for="" class="form-label">Adres :</label>
        <input type="text" class="form-control" asp-for="Adress">
    </div>
    <div class="form-group">
        <label for="" class="form-label">Cep Numarası :</label>
        <input type="number" class="form-control" asp-for="contactNumber">
    </div><br>

    <div class="form-group">
        <label for="cars">Lütfen listeden araba seçiniz:</label><br>
        <select name="cars" id="cars">
            <option value="Toyota Camry">Toyota Camry</option>
            <option value="Honda Accord">Honda Accord</option>
            <option value="Tesla Model S">Tesla Model S</option>
            <option value="BMW 7 Series">BMW 7 Series</option>
            <option value="Ford Mustang">Ford Mustang</option>
            <option value="Skoda Fabia">Skoda Fabia</option>
            <option value="Renault Clio">Renault Clio</option>
            <option value="Fiat Egea">Fiat Egea</option>
            <option value="Volkswagen Golf 5">Volkswagen Golf 5</option>
            <option value="Audi A7">Audi A7</option>
        </select>
    </div>
    <div class="form-group">
        <label for="start-date">Kiralama Başlangıç Tarihi:</label>
        <input type="date" id="start-date" name="start-date">
    </div>
    <div class="form-group">
        <label for="end-date">Kiralama Bitiş Tarihi:</label>
        <input type="date" id="end-date" name="end-date">
    </div>

    <button type="submit" class="btn btn-primary">Kaydet</button>
    <button type="submit" class="btn btn-danger"
            asp-action="Delete"
            asp-controller="Customers">
        Delete
    </button> <!--CustomersControllersdan alıyoruz-->
</form>

rentACarProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa Ekranı";
}

<div class="text-center">
    <h1 class="display-4">Araba Kiralama Sitesi Projesi</h1>
    <img src="~/images/rentresim.jpg" alt="Araba kiralama resmi" style="width: 100%; display: block; margin: 0 auto;">
</div>

rentACarProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - rentACarProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/rentACarProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">rentACarProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Müşterileri Görüntüle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Add">Müşteri Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Show">Araçları Görüntüle</a>
                        </li>
       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - rentACarProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>